apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ricardo-advanceweb-ingress
  namespace: ricardo-advancedweb
spec:
  ingressClassName: nginx
  rules:
  - host: advanceweb.duckdns.org
    http:
      paths:
      - path: /Home
        pathType: Prefix
        backend:
          service:
            name: web-svc
            port:
              number: 80